[client]
remoteHost=192.168.1.167
xdpRestoreToken=81c60d3b-dcbe-47e4-a827-ab7195a8b78e

[core]
computerName=citidel
coreMode=1
lastVersion=1.26.0.0

[gui]
closeReminder=false
enableUpdateCheck=false
logExpanded=true
shownFirstConnectedMessage=true
startCoreWithGui=true

[internalConfig]
clipboardSharing=true
clipboardSharingSize=@Variant(\0\0\0\x84\0\0\0\0\0\0\f\0)
defaultLockToScreenState=false
disableLockToScreen=false
hasHeartbeat=false
hasSwitchDelay=false
hasSwitchDoubleTap=false
heartbeat=5000
hotkeys\size=0
numColumns=5
numRows=3
protocol=1
relativeMouseMoves=false
screens\1\name=
screens\10\name=
screens\11\name=
screens\12\name=
screens\13\name=
screens\14\name=
screens\15\name=
screens\2\name=
screens\3\name=
screens\4\name=
screens\5\name=
screens\6\name=
screens\7\name=
screens\8\name=
screens\9\name=
screens\size=15
switchCornerArray\1\switchCorner=false
switchCornerArray\2\switchCorner=false
switchCornerArray\3\switchCorner=false
switchCornerArray\4\switchCorner=false
switchCornerArray\size=4
switchCornerSize=0
switchDelay=250
switchDoubleTap=250
win32KeepForeground=false
