include themes/EvilMorty.conf

font_family JetBrains Mono Nerd Font
font_size 11.0

background_opacity 0.78
dynamic_background_opacity yes

window_padding_width 10
window_border_width 1pt
single_window_margin_width 8
placement_strategy center

tab_bar_style separator
tab_separator "  "
tab_bar_min_tabs 2
active_tab_font_style bold

cursor_shape block
cursor_blink_interval 0.6

enable_audio_bell no
