# EvilMorty Kitty theme
# Matched to EvilMorty.colors

foreground            #8ee565
background            #030d05
selection_foreground  #020a04
selection_background  #6fc445

cursor                #00ff66
cursor_text_color     #020a04

url_color             #79dc4c
active_border_color   #79dc4c
inactive_border_color #5d9146
bell_border_color     #bfe04e

active_tab_foreground   #020a04
active_tab_background   #79dc4c
inactive_tab_foreground #5d9146
inactive_tab_background #051208
tab_bar_background      #030d05

mark1_foreground #020a04
mark1_background #79dc4c
mark2_foreground #020a04
mark2_background #bfe04e
mark3_foreground #020a04
mark3_background #ff5060

# ANSI colors
color0  #020a04
color8  #5d9146

color1  #ff5060
color9  #ff7a87

color2  #79dc4c
color10 #8fee56

color3  #bfe04e
color11 #d7f06a

color4  #54a637
color12 #6fc445

color5  #5f7d43
color13 #8ee565

color6  #00aa44
color14 #00ff66

color7  #8ee565
color15 #c8ff9a
